"""Stage 3: VLM-based Pseudo-Label Review using Qwen2.5-VL.

Implements the Review stage from the DART pipeline (arXiv:2407.09174).
Uses Qwen2.5-VL to verify pseudo-labels generated by Grounding DINO.

Two review strategies:
- "patch": Crops each detection and asks VLM to verify the class label.
- "full": Sends the full image with drawn annotations for holistic review.

Labels above auto_approve_threshold are auto-approved without VLM review.
Labels that fail VLM review are flagged for human annotation (Stage 4).
"""

import json
import logging
import re
import shutil
from pathlib import Path

import cv2
import numpy as np
import torch
from PIL import Image
from tqdm import tqdm
from transformers import AutoProcessor, Qwen2_5_VLForConditionalGeneration

logger = logging.getLogger("distill.vlm_review")


def _get_device(device_cfg: str) -> str:
    if device_cfg == "auto":
        return "cuda" if torch.cuda.is_available() else "cpu"
    return device_cfg


def _crop_patch(image: np.ndarray, bbox_xyxy: list[float], padding_ratio: float) -> np.ndarray:
    """Crop a detection patch from the image with padding for context.

    Args:
        image: Full image as numpy array (H, W, C).
        bbox_xyxy: Bounding box in [x1, y1, x2, y2] format.
        padding_ratio: Fraction of box size to add as padding.

    Returns:
        Cropped patch as numpy array.
    """
    h, w = image.shape[:2]
    x1, y1, x2, y2 = bbox_xyxy

    box_w = x2 - x1
    box_h = y2 - y1
    pad_x = box_w * padding_ratio
    pad_y = box_h * padding_ratio

    # Add padding and clamp to image bounds
    x1 = max(0, int(x1 - pad_x))
    y1 = max(0, int(y1 - pad_y))
    x2 = min(w, int(x2 + pad_x))
    y2 = min(h, int(y2 + pad_y))

    patch = image[y1:y2, x1:x2]

    # If patch is too small, pad it to at least 64x64
    ph, pw = patch.shape[:2]
    if ph < 64 or pw < 64:
        scale = max(64 / ph, 64 / pw)
        patch = cv2.resize(patch, None, fx=scale, fy=scale, interpolation=cv2.INTER_LINEAR)

    return patch


def _parse_vlm_response(response: str) -> tuple[bool, str]:
    """Parse VLM yes/no response.

    Args:
        response: VLM text output.

    Returns:
        Tuple of (is_approved, reason).
    """
    response_lower = response.strip().lower()

    # Check for explicit yes/no at the start
    if response_lower.startswith("yes"):
        reason = response.strip()[3:].strip().lstrip(",").lstrip(".").strip()
        return True, reason or "Approved by VLM"

    if response_lower.startswith("no"):
        reason = response.strip()[2:].strip().lstrip(",").lstrip(".").strip()
        return False, reason or "Rejected by VLM"

    # Fallback: search for yes/no anywhere
    if re.search(r"\byes\b", response_lower):
        return True, response.strip()
    if re.search(r"\bno\b", response_lower):
        return False, response.strip()

    # Default: reject if unclear
    return False, f"Unclear VLM response: {response.strip()}"


def run(config: dict) -> dict:
    """Run VLM-based review of pseudo-labels.

    Args:
        config: Pipeline configuration dictionary.

    Returns:
        Dictionary with review results.
    """
    review_cfg = config["vlm_review"]
    classes = config["classes"]

    if not review_cfg.get("enabled", True):
        logger.info("VLM review is disabled, auto-approving all labels")
        return _auto_approve_all(config)

    images_dir = Path(config["paths"]["data_dir"]) / "images"
    auto_labels_dir = Path(config["paths"]["labels_dir"]) / "auto"
    review_dir = Path(config["paths"]["review_dir"])
    approved_dir = Path(config["paths"]["labels_dir"]) / "approved"
    flagged_dir = Path(config["paths"]["labels_dir"]) / "flagged"

    for d in [review_dir, approved_dir, flagged_dir]:
        d.mkdir(parents=True, exist_ok=True)

    # Load detection metadata
    metadata_file = auto_labels_dir / "detection_metadata.json"
    if not metadata_file.exists():
        raise FileNotFoundError(
            f"Detection metadata not found: {metadata_file}. Run auto-labeling first."
        )

    with open(metadata_file) as f:
        all_detections = json.load(f)

    device = _get_device(review_cfg.get("device", "auto"))
    auto_approve_threshold = review_cfg.get("auto_approve_threshold", 0.65)
    padding_ratio = review_cfg.get("patch_padding_ratio", 0.15)
    strategy = review_cfg.get("strategy", "patch")

    logger.info("Loading Qwen VLM: %s", review_cfg["model_id"])
    processor = AutoProcessor.from_pretrained(review_cfg["model_id"])
    model = Qwen2_5_VLForConditionalGeneration.from_pretrained(
        review_cfg["model_id"],
        torch_dtype=torch.float16 if device == "cuda" else torch.float32,
        device_map=device if device == "cuda" else None,
    )
    if device != "cuda":
        model = model.to(device)
    model.eval()

    # Review statistics
    stats = {
        "total_images": 0,
        "total_detections": 0,
        "auto_approved": 0,
        "vlm_approved": 0,
        "vlm_rejected": 0,
        "images_fully_approved": 0,
        "images_flagged": 0,
        "rejections_per_class": {cls: 0 for cls in classes},
    }

    review_results = {}

    for img_name, detections in tqdm(all_detections.items(), desc="VLM Review"):
        if not detections:
            continue

        stats["total_images"] += 1
        img_path = images_dir / img_name

        if not img_path.exists():
            logger.warning("Image not found: %s", img_path)
            continue

        image = cv2.imread(str(img_path))
        if image is None:
            logger.warning("Failed to read image: %s", img_path)
            continue

        image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        img_h, img_w = image.shape[:2]

        approved_detections = []
        flagged_detections = []

        for det in detections:
            stats["total_detections"] += 1
            confidence = det["confidence"]
            class_name = det["class_name"]

            # Auto-approve high-confidence detections
            if confidence >= auto_approve_threshold:
                stats["auto_approved"] += 1
                det["review_status"] = "auto_approved"
                det["review_reason"] = f"Confidence {confidence:.3f} >= {auto_approve_threshold}"
                approved_detections.append(det)
                continue

            # VLM review for lower-confidence detections
            if strategy == "patch":
                approved, reason = _review_patch(
                    model, processor, image_rgb, det, class_name,
                    review_cfg, device, padding_ratio
                )
            else:
                approved, reason = _review_full_image(
                    model, processor, image_rgb, [det], classes,
                    review_cfg, device
                )

            det["review_status"] = "vlm_approved" if approved else "vlm_rejected"
            det["review_reason"] = reason

            if approved:
                stats["vlm_approved"] += 1
                approved_detections.append(det)
            else:
                stats["vlm_rejected"] += 1
                stats["rejections_per_class"][class_name] += 1
                flagged_detections.append(det)

        # Write approved labels
        if approved_detections:
            label_file = approved_dir / (img_path.stem + ".txt")
            lines = []
            for det in approved_detections:
                cx, cy, w, h = det["bbox_yolo"]
                lines.append(f"{det['class_idx']} {cx:.6f} {cy:.6f} {w:.6f} {h:.6f}")
            with open(label_file, "w") as f:
                f.write("\n".join(lines))

        # Track flagged images (for human review)
        if flagged_detections:
            stats["images_flagged"] += 1
            flagged_file = flagged_dir / (img_path.stem + ".json")
            with open(flagged_file, "w") as f:
                json.dump(
                    {
                        "image": img_name,
                        "approved": approved_detections,
                        "flagged": flagged_detections,
                    },
                    f,
                    indent=2,
                )
            # Copy the original auto-label too for reference
            auto_label = auto_labels_dir / (img_path.stem + ".txt")
            if auto_label.exists():
                shutil.copy2(auto_label, flagged_dir / (img_path.stem + ".txt"))
        else:
            stats["images_fully_approved"] += 1

        review_results[img_name] = {
            "approved_count": len(approved_detections),
            "flagged_count": len(flagged_detections),
        }

    # Save review summary
    summary_file = review_dir / "review_summary.json"
    with open(summary_file, "w") as f:
        json.dump({"stats": stats, "per_image": review_results}, f, indent=2)

    logger.info("VLM Review complete:")
    logger.info("  Total detections reviewed: %d", stats["total_detections"])
    logger.info("  Auto-approved (high conf): %d", stats["auto_approved"])
    logger.info("  VLM approved: %d", stats["vlm_approved"])
    logger.info("  VLM rejected: %d", stats["vlm_rejected"])
    logger.info("  Images fully approved: %d", stats["images_fully_approved"])
    logger.info("  Images flagged for human review: %d", stats["images_flagged"])

    return {
        "approved_labels_dir": str(approved_dir),
        "flagged_labels_dir": str(flagged_dir),
        "review_summary": str(summary_file),
        "stats": stats,
    }


def _review_patch(
    model, processor, image: np.ndarray, detection: dict,
    class_name: str, review_cfg: dict, device: str, padding_ratio: float
) -> tuple[bool, str]:
    """Review a single detection by cropping and asking VLM."""
    patch = _crop_patch(image, detection["bbox_xyxy"], padding_ratio)
    patch_pil = Image.fromarray(patch)

    prompt_template = review_cfg.get(
        "patch_review_prompt",
        'Is this a {class_name}? Answer "yes" or "no" with a brief reason.',
    )
    prompt_text = prompt_template.format(class_name=class_name)

    # Build Qwen VL message format
    messages = [
        {
            "role": "user",
            "content": [
                {"type": "image", "image": patch_pil},
                {"type": "text", "text": prompt_text},
            ],
        }
    ]

    text = processor.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
    inputs = processor(
        text=[text],
        images=[patch_pil],
        return_tensors="pt",
        padding=True,
    ).to(device)

    with torch.no_grad():
        output_ids = model.generate(**inputs, max_new_tokens=100)

    # Decode only the generated tokens
    generated_ids = output_ids[:, inputs["input_ids"].shape[1]:]
    response = processor.batch_decode(generated_ids, skip_special_tokens=True)[0]

    return _parse_vlm_response(response)


def _review_full_image(
    model, processor, image: np.ndarray, detections: list[dict],
    classes: list[str], review_cfg: dict, device: str
) -> tuple[bool, str]:
    """Review detections on the full image with drawn bounding boxes."""
    # Draw bounding boxes on image copy
    annotated = image.copy()
    det_descriptions = []

    for i, det in enumerate(detections):
        x1, y1, x2, y2 = [int(v) for v in det["bbox_xyxy"]]
        cv2.rectangle(annotated, (x1, y1), (x2, y2), (0, 255, 0), 2)
        cv2.putText(
            annotated, f"{i+1}: {det['class_name']}",
            (x1, y1 - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0, 255, 0), 2,
        )
        det_descriptions.append(
            f"Detection {i+1}: '{det['class_name']}' at box [{x1},{y1},{x2},{y2}]"
        )

    annotated_pil = Image.fromarray(annotated)
    prompt_template = review_cfg.get("full_image_review_prompt", "Review the detections.")
    prompt_text = prompt_template.format(detections="\n".join(det_descriptions))

    messages = [
        {
            "role": "user",
            "content": [
                {"type": "image", "image": annotated_pil},
                {"type": "text", "text": prompt_text},
            ],
        }
    ]

    text = processor.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
    inputs = processor(
        text=[text],
        images=[annotated_pil],
        return_tensors="pt",
        padding=True,
    ).to(device)

    with torch.no_grad():
        output_ids = model.generate(**inputs, max_new_tokens=300)

    generated_ids = output_ids[:, inputs["input_ids"].shape[1]:]
    response = processor.batch_decode(generated_ids, skip_special_tokens=True)[0]

    return _parse_vlm_response(response)


def _auto_approve_all(config: dict) -> dict:
    """Auto-approve all labels when VLM review is disabled."""
    auto_labels_dir = Path(config["paths"]["labels_dir"]) / "auto"
    approved_dir = Path(config["paths"]["labels_dir"]) / "approved"
    approved_dir.mkdir(parents=True, exist_ok=True)

    count = 0
    for label_file in auto_labels_dir.glob("*.txt"):
        shutil.copy2(label_file, approved_dir / label_file.name)
        count += 1

    logger.info("Auto-approved all %d label files (VLM review disabled)", count)

    return {
        "approved_labels_dir": str(approved_dir),
        "flagged_labels_dir": None,
        "review_summary": None,
        "stats": {"auto_approved": count, "vlm_rejected": 0},
    }
